### ISSUE TITLE
Cache configuration

### ISSUE THREAD

**Issue by DragonBanana** [stelar7/L4J8#15]
Hi,
i started to use your library and I would like to manage caching configuration, but I didn't find anything. Is it possible to set for how much time to keep some data (both in memory and on disk)?

**Comment by manuelwaldner** [comment]
If you look into the Constructor of the L4J8 class you see, that there is a line which sets the CacheProvider of the DataCall.class. 
I dont have much time right now, but maybe you can figure it out yourself if you inspect the DataCall code and thr CacheProvider etc.

**Comment by manuelwaldner** [comment]
I looked into my code and here is a short example how to use a `FileSystemCacheProvider` with custom TimeToLive times for specific endpoints.

```
L4J8 l4j8 = new L4J8(SecretFile.CREDS);
FileSystemCacheProvider cacheProvider = new FileSystemCacheProvider(getFilesDir().resolve(L4J8_CACHE_DIR));
CacheLifetimeHint hints = new CacheLifetimeHint();
hints.add(URLEndpoint.V3_CHAMPION_ROTATIONS, TimeUnit.DAYS.toMillis(7L)); // 1 week
cacheProvider.setTimeToLive(hints);
DataCall.setCacheProvider(cacheProvider);
```

**Comment by stelar7** [comment]
The memory cache is kinda wonky at the moment, and does not support the cache hints properly.
As for how to set the TTL, see the comment above from manuelwaldner.

The default values are shown here https://github.com/stelar7/L4J8/blob/a639248e2509b91aee1cb64c493c4982881d24b0/src/main/java/no/stelar7/api/l4j8/basic/cache/CacheLifetimeHint.java#L38-L65

**Comment by stelar7** [comment]
I have a fix for the memory cache in the works, but no ETA. Most likely late October...
