### ISSUE TITLE
Gson has previously Deserialized to Double

### ISSUE THREAD

**Issue by lessonz** [stelar7/L4J8#16]
https://github.com/stelar7/L4J8/blob/07d84d58c301c273f9e9d37b42b32c4ceb440156/src/main/java/no/stelar7/api/l4j8/pojo/shared/BaseSpellData.java#L169

Does this work for you when called by way of a StaticChampion? It doesn't work for me, but I'm calling it from Kotlin. I don't think that should be an issue, but I felt I should mention it just in case. Something like what's happening here: https://stackoverflow.com/questions/15507997/how-to-prevent-gson-from-expressing-integers-as-floats.

**Comment by stelar7** [comment]
Turns out, its not really an issue before you try to assign a variable from the list.
