### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by splitzyo** [stelar7/L4J8#2]
Hello, 
I was trying to use your library in my Android Studio project and ran into this error : 

> Error:java.lang.ClassNotFoundException: Class javafx.util.Pair not found
> Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\6.jar --output Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\desugar\debug\7.jar --input Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\15.jar --output Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\desugar\debug\16.jar --input Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --output Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\desugar\debug\4.jar --input Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\18.jar --output Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\desugar\debug\19.jar --input Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --output Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\desugar\debug\6.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\classes\debug --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\0.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\2.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\4.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\6.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\7.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\8.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\9.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\10.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\11.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\12.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\13.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\14.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\15.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\16.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\17.jar --classpath_entry Z:\Development Projects\LeagueofLegends\app\build\intermediates\transforms\stackFramesFixer\debug\18.jar --bootclasspath_entry C:\Users\User\AppData\Local\Android\Sdk\platforms\android-26\android.jar --bootclasspath_entry C:\Users\User\AppData\Local\Android\Sdk\platforms\android-26\optional\org.apache.http.legacy.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_91\jre\lib\resources.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_91\jre\lib\rt.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_91\jre\lib\jsse.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_91\jre\lib\jce.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_91\jre\lib\charsets.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_91\jre\lib\jfr.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}
Error:java.lang.ClassNotFoundException: Class javafx.util.Pair not found

I m already using java 8 and I tried to clean - rebuild the project and still got  the same error.
I have also set `multiDexEnabled` to `true`.
The library dependency is set correctly.
My Android Studio version is : 3.0.1 and I m using Gradle 3.0.1
Any help would be really appreciated.

**Comment by stelar7** [comment]
Seems like an issue with Java8 on Android. I'll fix it soon (like 3-4 hours)
