### ISSUE TITLE
Found another APIEnumNotUpToDateException

### ISSUE THREAD

**Issue by IKERNEII** [stelar7/L4J8#4]
The enum no.stelar7.api.l4j8.basic.constants.types.GameQueueType is missing the type 1020!

**Comment by stelar7** [comment]
This is fixed in version 1.4.2

**Comment by IKERNEII** [comment]
Is this version already out?

**Comment by stelar7** [comment]
Just added it, it should be out now

**Comment by IKERNEII** [comment]
Thank alot
